version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_db_root_password
      - MYSQL_DATABASE=your_db_name
      - MYSQL_USER=your_db_user
      - MYSQL_PASSWORD=your_db_password
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: ./web
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    volumes:
      - ../html:/var/www/html
  wordmove:
    build: ./wordmove
    depends_on:
      - db
    volumes:
      - ../html:/home/html
    command: /bin/sh -c "while true; do echo hello world; sleep 1; done"
volumes:
  db-data:
    driver: local
